
version: "3"
services:
  flaskapp-postgres:
    container_name: flaskapp-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anim
    ports:
      - 5432:5432

  flaskapp:
    container_name: flaskapp
    build: .
    image: flashapp
    ports:
      - 80
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - flaskapp-postgres
    environment:
      - VIRTUAL_HOST=flaskapp.docker
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - DATABASE_HOST=flaskapp-postgres
      - DATABASE_PORT=5432




 